### ISSUE TITLE
WebSocketError: unable to receive websocket message with uwsgi in emperor mode

### ISSUE THREAD

**Issue by papasax** [jrief/django-websocket-redis#101]
Hi,

I installed the demo on Heroku with uwsgi in emperor mode as described in the doc. It still works, but i get this in my log:

[2015-06-23 14:02:17,890 wsgi_server] WARNING: WebSocketError:  
Jun 23 05:02:18 agile-plains-4225 app/web.1:  Traceback (most recent call last): 
Jun 23 05:02:18 agile-plains-4225 app/web.1:    File "./ws4redis/wsgi_server.py", line 92, in __call__ 
Jun 23 05:02:18 agile-plains-4225 app/web.1:      recvmsg = RedisMessage(websocket.receive()) 
Jun 23 05:02:18 agile-plains-4225 app/web.1:    File "./ws4redis/uwsgi_runserver.py", line 31, in receive 
Jun 23 05:02:18 agile-plains-4225 app/web.1:      raise WebSocketError(e) 
Jun 23 05:02:18 agile-plains-4225 app/web.1:  WebSocketError: unable to receive websocket message 

This used to work very well. I did not change any library for 6 months.

The only difference i can see is that uwsgi launches with pcre jit disabled (I don't know why, Rodrigo told me that probably the heroku stack changed). It looks like the uwsgi internal router really needs pcre.

**Comment by jrief** [comment]
Recently I've build uwsgi-2.0.7 as rpm for Fedora-20. The Specfile says in BuildRequires: pcre-devel
and since my route example uses regular expressions, this is a good explanation.
Can you reinstall uwsgi inside a virtualenv on Heroku? This would fix your problem.

**Comment by depaolim** [comment]
2015-06-23 14:12 GMT+02:00 Alexandre Desenfant <notifications@github.com>:

> Hi,
>
> I installed the demo on Heroku with uwsgi in emperor mode as described in
> the doc. It still works, but i get this in my log:
>
> [2015-06-23 14:02:17,890 wsgi_server] WARNING: WebSocketError:
>
> Jun 23 05:02:18 agile-plains-4225 app/web.1: Traceback (most recent call
> last):
> Jun 23 05:02:18 agile-plains-4225 app/web.1: File
> "./ws4redis/wsgi_server.py", line 92, in *call*
> Jun 23 05:02:18 agile-plains-4225 app/web.1: recvmsg =
> RedisMessage(websocket.receive())
> Jun 23 05:02:18 agile-plains-4225 app/web.1: File
> "./ws4redis/uwsgi_runserver.py", line 31, in receive
> Jun 23 05:02:18 agile-plains-4225 app/web.1: raise WebSocketError(e)
> Jun 23 05:02:18 agile-plains-4225 app/web.1: WebSocketError: unable to
> receive websocket message
>
> This used to work very well. I did not change any library for 6 months.
>
> The only difference i can see is that uwsgi launches with pcre jit
> disabled (I don't know why, Rodrigo told me that probably the heroku stack
> changed). It looks like the uwsgi internal router really needs pcre.
>
yes, I do think so

if you used this:
http://django-websocket-redis.readthedocs.org/en/latest/running.html#django-with-websockets-for-redis-as-a-stand-alone-uwsgi-server-in-emperor-mode

route = ^/ws uwsgi:/var/tmp/web.socket,0,0
route = ^/ uwsgi:/var/tmp/django.socket,0,0

than you need routing

And uWSGI needs pcre for routing:

http://uwsgi-docs.readthedocs.org/en/latest/InternalRouting.html#the-internal-routing-table

"The internal routing table is a sequence of ‘’rules’’ executed one after
another (forward jumps are allowed too). Each rule is composed by a
‘’subject’‘, a ‘’condition’’ and an ‘’action’‘. The ‘’condition’’ is
generally a PCRE regexp applied to the subject: if it matches, the action
is triggered. Subjects are request’s variables. Currently the following
subjects are supported:"

bye,
Marco

**Comment by papasax** [comment]
Hi Jacob, I did empty my repository to force a compile of uwsgi on Heroku and got this at the end of the build:
################# uWSGI configuration #################
pcre = True
kernel = Linux
malloc = libc
execinfo = False
ifaddrs = True
ssl = True
zlib = True
locking = pthread_mutex
plugin_dir = .
timer = timerfd
yaml = embedded
json = False
filemonitor = inotify
routing = True
debug = False
capabilities = False
xml = libxml2
event = epoll
############## end of uWSGI configuration #############
It looks like pcre is enabled. Rodrigo told me that jit is only an optimization,it is not required for uWSGI internal routing, any pcre version will be good for it.
I can still access a few pages on my server until i get the WebSocketError, and then nothing...

**Comment by papasax** [comment]
Funny,
it also get this error when i try a simple GET /fr/le-temps-dun-regard/
NoReverseMatch: Reverse for 'livre_detail' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'fr/(?P<slug>[-\\w\\d]+)/$']
Actually none of my pages with a slug work.
Regular Expression does not work with Django neither!!!! This would mean that pcre is just broken on heroku?

**Comment by depaolim** [comment]
2015-06-23 15:43 GMT+02:00 Alexandre Desenfant <notifications@github.com>:

> Funny,
> it also get this error when i try a simple GET /fr/le-temps-dun-regard/
> NoReverseMatch: Reverse for 'livre_detail' with arguments '('',)' and
> keyword arguments '{}' not found. 1 pattern(s) tried: [u'fr/(?P[-\w\d]+)/$']
> Actually none of my pages with a slug work.
> Regular Expression does not work with Django neither!!!! This would mean
> that pcre is just broken on heroku?
>
does python rely on perl regular expressions?!? ;-)
http://www.pcre.org/

<any kind> of regular expressions is just broken on heroku? ;-)

any hypotesis is funny

Marco

**Comment by papasax** [comment]
Well sometimes there is a little magic....Especially when i don't sleep enough. Perl and Python could share a c library for example but you are right, heroku is not down yet. I fixed my cache configuration and resolve works better. I still have the "unable to receive websocket message" in my log. The Websocket seems to work.

**Comment by depaolim** [comment]
2015-06-23 17:11 GMT+02:00 Alexandre Desenfant <notifications@github.com>:

> Well sometimes there is a little magic....Especially when i don't sleep
> enough. Perl and Python could share a c library for example but you are
> right, heroku is not down yet. I fixed my cache configuration and resolve
> works better. I still have the "unable to receive websocket message" in my
> log. The Websocket seems to work.
>
happy to hear that
bye,
Marco
