### ISSUE TITLE
Set expire when message is sent to client

### ISSUE THREAD

**Issue by AgDude** [jrief/django-websocket-redis#102]
Consider this use case: I publish a message to a user outside of the request cycle (a celery task for example). I want to send this to the user even if he isn't currently connected, so I set an expire of 30 minutes. It seems that the current implementation will send this message again every time the user connects in that 30 minutes.

Is there a way to set the expire time when the websocket actually sends the message to the client? Alternatively the message could be deleted entirely, but my preference is that it be persisted for something like 10 seconds after it is sent.

If that doesn't exist, consider this a feature request. I am not familiar with this codebase, but if given a little direction on where to start, I would consider opening a PR.

**Comment by AgDude** [comment]
After a little further reading, this is relatively easy by sub-classing `RedisSubscriber.send_persited_messages`. In that context `channel` is the redis key.

**Comment by jrief** [comment]
Ok, good to know its possible. Would you mind to add some notes to the docs? Thanks, Jacob

**Comment by AgDude** [comment]
I have found a major flaw in my approach, or more accurately, the whole concept of persisted messages. It appears there is only one key in redis per channel, which gets overwritten if I send a new message, so the client will only ever get the most recent message when it connects.

If I am wrong about this please help me better understand. I am going to spend a little time this morning reading more of the source.

My first thought is that persisted messages need to go into a redis list instead of a simple key, but then redis won't handle expiring for us at all.

**Comment by AgDude** [comment]
@jrief My suggestion on this moving forward is to remove persisted message support entirely. Redis is a great tool for a message queue, but IMO that is really outside the scope of a websocket library. As long as there is a hook for users to attach their own code when a socket is opened, there shouldn't be a need to persist them through the django-websocket-redis.

I like the overall approach you have taken in this library, thank you.

**Comment by jrief** [comment]
@AgDude 
This is not a good idea. If a client WS connection broke and then reconnects, the client fetches the old message. Therefore the persistence feature of Redis is really useful.
On the other hand, if a client sends upstream, the Django-loop has to collect that data sometimes, asynchronously. This only works with persisted messages.

**Comment by jrief** [comment]
A had a look at your PR. Something I don't understand is why you have to add up the expire timeout. Doesn't do this Redis automatically for us?

**Comment by AgDude** [comment]
Redis doesn't handle expire time within a list, so each item in the list includes the expire time. Redis only handles ttl on the key itself. When we add a new item to the list which expires later than the current key, we need to reset the key ttl to match the new item.  

With the implementation we aren't relying on the redis expire for anything except cleanup.

**Comment by jrief** [comment]
@AgDude ah, OK. Something I didn't pay attention so far. Well then your PR makes sense.
