### ISSUE TITLE
RedisMessage failes on Python 3

### ISSUE THREAD

**Issue by jokerejoker** [jrief/django-websocket-redis#105]
I get the following error when using RedisMessage on version 0.4.4

```
  File ".../ws4redis/redis_store.py", line 69, in __new__
    return six.binary_type.__new__(cls, value)
TypeError: string argument without an encoding
```

Python 3.4.3 and Django 1.7.8

**Comment by jrief** [comment]
I think the project stated quite clearly that is does not run with Python-3 until the lowlevel WS lib is Py3 safe.
