### ISSUE TITLE
 issue about example

### ISSUE THREAD

**Issue by chelseafeng** [jrief/django-websocket-redis#111]
The bug:'ws4redis.exceptions.WebSocketError: unable to receive websocket message' bothers me for a long time when i run the example using django runserver  or uwsgi configuration files  following the docs in django-websocket-redis,tell me why!

**Comment by jrief** [comment]
how is the Javascript part working? Did you start to debug on the client.
Anyway, the way you ask, is to helpful for me to give you an useful answer.
