### ISSUE TITLE
Looking for connection id or similar

### ISSUE THREAD

**Issue by onelson** [jrief/django-websocket-redis#112]
Hi there, I'm hoping to key some other data off of each client connection, and in other websocket implementations I've seen some kind of `on_connect()` callback that receives a connection object or something that could be used to identify the client.

Is there something like this I can do for this project?

I see in the RedisStore class there is code that examines the logged in user, but we don't have logins on our app and just need to identify each specific client.

Cheers,
Owen

**Comment by jrief** [comment]
Hi @onelson 
what about using the sessionId ? Using that you could assign each connection to a user.
If you absolutely require an Id generated by some client code, you could add a hook to DWR.

**Comment by onelson** [comment]
I was unaware there *was* a session id for unauthenticated users. I'll look at this tactic. Wasn't looking to generate the id on the client side. Client shouldn't care about what it's id is, only that it is receiving messages tailored for its interests.

Is there some part of the API that might be good for tracking clients as they connect so that messages could be sent specifically to them? I must be missing something, perhaps in setting up channels, that could be used to achieve this.

**Comment by jrief** [comment]
well, if you don't use any session data, you have to force the generation of the session cookie. I think you can try with:
```
if SESSION_KEY not in request.session:
    request.session.cycle_key()
```
