### ISSUE TITLE
Django 1.9 incompatibility: Error importing module: 'cannot import name 'STATUS_CODE_TEXT'

### ISSUE THREAD

**Issue by gitaarik** [jrief/django-websocket-redis#125]
See Django's release notes:
https://docs.djangoproject.com/en/1.9/releases/1.9/#miscellaneous

> django.http.responses.REASON_PHRASES and django.core.handlers.wsgi.STATUS_CODE_TEXT have been removed. Use Python’s stdlib instead: http.client.responses for Python 3 and httplib.responses for Python 2.

ws4redis uses it here:
https://github.com/jrief/django-websocket-redis/blob/master/ws4redis/wsgi_server.py#L10

I'm working on a pull request for this.

**Comment by gitaarik** [comment]
Having something already:
https://github.com/gitaarik/django-websocket-redis/commit/1c73764c0d02e0f4bf3c507ea854565346c4e80a

Will first test this, then make a pull request.

**Comment by gitaarik** [comment]
Ok here is it, tests succeeded on my machine for Python 2. Testing Python 3 wasn't straightforward as gevent still hasn't released a Python 3 compatible version (next version 1.1 will have it).

Travis is testing it now, expecting it to pass.

https://github.com/jrief/django-websocket-redis/pull/126

**Comment by jrief** [comment]
closed via #126
