### ISSUE TITLE
How use django web socket in angular js for push notification?

### ISSUE THREAD

**Issue by Gauravwagh** [jrief/django-websocket-redis#136]
I am trying to use the django web socket in angular js for push notification. As my angular application is different and web application is different. So i did a little part. I am able to send notification but i dont know how to push that to each user as front-end app and back end app is different.

**Comment by jrief** [comment]
Did you already have a look at this example http://django-angular.awesto.com/threeway_databinding/ ?
This presumably is what you need.

**Comment by Gauravwagh** [comment]
Hi Jacob,

Thank you very much for your help.

**Comment by nanuxbe** [comment]
This question looks like it's been answered, so I am closing this issue.
