### ISSUE TITLE
ws4redis does not communicate behind corporate firewalls

### ISSUE THREAD

**Issue by matteofattore-nextage** [jrief/django-websocket-redis#144]
Hello,

we are successfully using ws4redis library in our app since several months, but we encountered a problem when serving realtime data in a few repeatable situation behind a corporate firewall belonging to some companies (our costumer). It seems like the firewall blocks the websocket so they don't see data in the browser. Is it expected to support a "fallback" policy to alternative communication channels like sockjs and others do ?

**Comment by jrief** [comment]
well, you try with long polling, but that's out of scope of this library. This library does not claim to offer any kinds of SSE, it only claims to offer websockets.

**Comment by matteofattore-nextage** [comment]
Sorry, I don't have much experience in long polling and in what it's different from standard websocket use.


In my case the browser gives the following error 

too many missed heartbeats

Do you have any references that can help me figure out a solution for my problem ?
