### ISSUE TITLE
Admin password not provided in testing documentaiton

### ISSUE THREAD

**Issue by mcgeeco** [jrief/django-websocket-redis#147]
Hi. Following the testing documentation, and while the seed data includes an admin user, the password isn't provided anywhere. Should that not be noted somewhere? Sorry if I've missed it.

(I'll happily add it in if someone knows what it is...)

**Comment by jrief** [comment]
The demo app doesn't require an admin user to function properly. However, if you want to access the backend, create a user with ``./manage createsuperuser`` as mentioned in the Django docs.

**Comment by mcgeeco** [comment]
I know it's not necessary but the steps in the [documentation](https://django-websocket-redis.readthedocs.org/en/latest/testing.html#a-simple-chat-server) are quite clear and well-prepared. However, it says "Point a browser onto http://localhost:8000/admin/, login and add additional users." That's not possible without either first creating your own superuser (which isn't mentioned) or knowing the password for the admin user that's created in the loaddata step (which I've figured out is 'secret'). Just thought I'd add that in.. if you like?

**Comment by jrief** [comment]
Ups, you're right. I'll have to fix that!

**Comment by mcgeeco** [comment]
Does this look all right?
https://github.com/jrief/django-websocket-redis/pull/148
