### ISSUE TITLE
Latest git version is broken with Chrome

### ISSUE THREAD

**Issue by roidelapluie** [jrief/django-websocket-redis#152]
![fail](https://cloud.githubusercontent.com/assets/291750/12224524/697e0cf6-b7f3-11e5-98d2-a38cde35bcfe.png)

**Comment by jrief** [comment]
@ErwinJunge is this cause by your patch?
Could you please provide a solution, otherwise I have to revert #149

**Comment by roidelapluie** [comment]
It looks like this would be fixed if we get #151 in order?

**Comment by roidelapluie** [comment]
@jrief this would have been catched by #143 as well...

**Comment by ErwinJunge** [comment]
This is indeed caused by me. The fix is in #151, which I will gladly fix up tomorrow if the original author doesn't.
On Jan 10, 2016 23:48, Julien Pivotto <notifications@github.com> wrote:It looks like this would be fixed if we get #151 in order?

**Comment by timeseer** [comment]
I got this error on `example` project too. I installed 0.4.5 version via pip.

**Comment by jrief** [comment]
@roidelapluie could you please retest – I'm currently too busy with other stuff.

**Comment by roidelapluie** [comment]
0.4.5 is fine

**Comment by jrief** [comment]
@ErwinJunge would you like to add a description to the changelog for version 0.4.6? Then please add a line here, without extra pull request. Otherwise I'll use you PR description.
Thanks for patching and testing.

**Comment by ErwinJunge** [comment]
"Added support for the Sec-WebSocket-Protocol header." sounds fine to me.
