### ISSUE TITLE
Client Disconnect Callback on Server

### ISSUE THREAD

**Issue by zivziv77** [jrief/django-websocket-redis#156]
Hi

I know it has been asked a lot and I guess the question is that still there is no callback on the server to know when connection with client is broken for some reason.

I wanted to know if possible as workaround to override the redisSubscriber and use the release function to know when the connection is broken.

or is there any other way to do that?

Thanks a lot for a great project

Ziv

**Comment by jrief** [comment]
I don't feel very comfortable if custom code is added to this loop. This can result very easily in a blocking server. Can you please explain what kind of action you want to perform server-side, when a client disconnects. Something I could imagine to implement, is sending a message to Redis informing other listeners about this.

**Comment by zivziv77** [comment]
I need to know if users are online to send them an automatic invitation, so I need to update redis or other http server about users online and offline.

I saw there is implementation  authorize channels when users are connected, I need exactly the same for offline users.

Thanks a lot!

**Comment by zivziv77** [comment]
better is only update redis since update other http can harm performance.
if it is doable that would be great!

**Comment by zivziv77** [comment]
Hi again,
sorry to bother you it would be nice if you can tell me if that is doable.
Since this is critical to my project I need to know whether using the release method to update redis if user is offline is ok or there are alternatives better ways to do that.

Thanks for your help

Ziv

**Comment by zivziv77** [comment]
Update fro people who will need to do it.
It is possible to inherit from redisSubscriber and override the release method and know when a socket/user is closed.

make sure not to do any blocking operations over there

**Comment by domface** [comment]
@zivziv77, how are you getting information on the user about this? request.user yields Anonymous user even if the user is logged in. The websocket doesn't get any information about the logged in user.

**Comment by zivziv77** [comment]
Hi

I was using the ws4redis without user login but in broadcast mode.
The channel I am listening is the user identifier for me.

So I guess that need a bit more investigation for users mode.

Ziv
