### ISSUE TITLE
override WS4REDIS_SUBSCRIBER

### ISSUE THREAD

**Issue by zivziv77** [jrief/django-websocket-redis#159]
I am trying to override  and doing my implementation of WS4REDIS_SUBSCRIBER with overriding the release function to inform when web socket is closed.

It doesn't seem to work.
anyone here can help please?

from ws4redis.subscriber import RedisSubscriber
class RDASubscriber(RedisSubscriber):

    def release(self):
        print ("hello")
        super(RDASubscriber,self).release()

WS4REDIS_SUBSCRIBER = 'myapp.subscriber.RDASubscriber.'

**Comment by zivziv77** [comment]
It is too bad that no one is answering here since it is a great project which should be maintained much better.
Anyway i had a problem in my path in the settings and I fixed that

**Comment by jrief** [comment]
Do you really believe that maintainers of OSS do not have any other stuff to do, than answering any kind of questions. Get paid support, if you need assistance!

**Comment by zivziv77** [comment]
No problem Jacob.

I am new to python and just came from many years on java to python and what I like here is the community of people helping each other, which is hardly exist in java.
if you require paid support you should say so in the beginning.
I was not aware that for any question/problem there is a need to pay. We were talking on other issue and you answered really fast then you stop responding.

I think that for the paying issue we can talk over mail.
Can you please specify your mail?

Ziv
