### ISSUE TITLE
dynamically created channels, aside from users, groups, sessions, and broadcast

### ISSUE THREAD

**Issue by domface** [jrief/django-websocket-redis#162]
Hi jrief,

Thanks a bunch for putting this library together.

I have a special use case whereby i have regions(in my case the facility), and within those regions i have channels. Each region may have n number of channels, which are stored in a postgres DB.

When the client first calls the DB to see how many channels are in a given region, i want to be able to add those channels into the websocket URL:

`ws://docker.box:32773/ws/region?subscribe-channelA&publish-channelA&subscribe-channelB&publish-channelB&subscribe-channelC&subscribe-ballsack&publish-ballsack&echo` etc....

The reason being is because i want to be able to have one open websocket, but subscriptions across a dynamic range of channels. Does it make sense to do it in this implementation? Perhaps grab the keys inside redis to populate the channels?

A region can have many channels, and the channels all depends on their parent region.

**Comment by jrief** [comment]
I read this twice, but did not understand your needs.
