### ISSUE TITLE
Hooking into django model changes.

### ISSUE THREAD

**Issue by Xorso** [jrief/django-websocket-redis#163]
I have been looking into implementing this library and wanted to know if there was a simple way of publishing changes that occur to models. For instance, if I am pulling data from a Jobs table, and someone adds a new job I would like that job to show up for every client connected. Would I need to override the `save` method for each model I create?

**Comment by jrief** [comment]
That's a bit off-topic.
It all depends on your needs and implementation. I personally would do these things in the controller (aka View class).
