### ISSUE TITLE
websocket.receive: UnicodeError 'ascii' 

### ISSUE THREAD

**Issue by bbaobelief** [jrief/django-websocket-redis#180]
Send Chinese error
INFO: websocket.receive: UnicodeError 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)

**Comment by jrief** [comment]
when sending what?

**Comment by domface** [comment]
I found that upgrading to Python3 solves a lot of these issues, particularly with this library.

**Comment by bbaobelief** [comment]
@jrief @domface 
**python2.7,django1.8,  python manage.py runserver**

**I try to send the Chinese, the link will be disconnected**

`09:44:23	command:	/send 123412341234
09:44:23	sent:	123412341234
09:44:23	received:	123412341234
09:44:31	command:	/send 中文
09:44:31	sent:	中文
09:44:31	system:	connection closed, ws://127.0.0.1:81/ws/public?subscribe-broadcast&publish-broadcast&echo`

**Comment by yguarata** [comment]
@bbaobelief a workaround for this is to convert your string into char codes before sending messages (using String.charCodeAt), and convert it back when you receive a message from the websocket (using String.fromCharCode). This is ugly but solves the issue. Not that you can use JSON.stringify to convert the char codes array into string, and vice versa.

```javascript
function to_char_code(str) {
	var char_codes = [];
	for (var i=0; i < str.length; i++) {
		char_codes.push(str.charCodeAt(i));
	}
	return char_codes;
}

function from_char_code(char_codes) {
	var str = "";
	for (var i=0; i < char_codes.length; i++) {
		str += String.fromCharCode(char_codes[i]);
	}
	return str;
}
```

**Comment by bbaobelief** [comment]
@yguarata Thanks， I am now using JS to solve the problem,

  var classObj=
    {
      ToUnicode:function(str) 
      {
        return escape(str).replace(/%/g,"\\").toLowerCase();
      },
      UnUnicode:function(str)
      {
        return unescape(str.replace(/\\/g, "%"));
      }
    }
