### ISSUE TITLE
rest-framework

### ISSUE THREAD

**Issue by nux17** [jrief/django-websocket-redis#197]
Hello,

I'm using django-rest-framework and want to implement your websocket module over it.

I can I manage to route a message to different views? I searched in the docs, but I can't find a real example of how to do this.

I would like to send something like 
{
   method: GET
   url : /users
}

and sends me back users.

**Comment by jrief** [comment]
Hmmm, the RESTframework never had websockets in mind. What I would do is to use the REST Serializers without the REST Views. Then at least you get the benefits for serialization.
In my opinion List- and Detail-Views, don't really make sense in a websocket context.
