### ISSUE TITLE
failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 0

### ISSUE THREAD

**Issue by camilonova** [jrief/django-websocket-redis#207]
Thank you for this awesome package.

I have this problem:
![screen_shot_2016-10-05_at_11_17_51_am](https://cloud.githubusercontent.com/assets/202559/19122021/4b43a6b4-8aee-11e6-9a56-200daeb3bb58.png)

I'm using:
```
Django==1.9.9
gevent==1.1.2
django-redis==4.4.4
django-websocket-redis==0.4.6
```

On Python 3.5 and Nginx 1.10

**Comment by jrief** [comment]
That message does not originate from the ws4redis library. Presumably it's from some tier in between. Please dig further.

**Comment by camilonova** [comment]
I only have nginx in between, any advice on where should I look?

**Comment by camilonova** [comment]
Using the current HEAD https://github.com/jrief/django-websocket-redis/commit/88006ddef9bc4c04523474f3ba5fde6c62158ae1 fixes the issue.

It was a problem with ws4redis library, but I can't tell exactly why. I just installed the current master branch and works perfect.
