### ISSUE TITLE
Please release 0.4.7

### ISSUE THREAD

**Issue by camilonova** [jrief/django-websocket-redis#209]
Last release was in January 2016.

This could be a great time to make a new release with all fixes and improvements made so far.

**Comment by jrief** [comment]
Thanks for reminding me. I will try later today.

**Comment by camilonova** [comment]
Thank you.

**Comment by jrief** [comment]
done.

I sorry for the delay. Currently I'm not working actively on any project which requires ws4redis, therefore I didn't look too much after that project.
