### ISSUE TITLE
Relase a new version with support for Django 1.11 to PyPi

### ISSUE THREAD

**Issue by poxip** [jrief/django-websocket-redis#227]
Hi, I see support for Django 1.11 has been added (https://github.com/jrief/django-websocket-redis/commit/35a7625192babfd5d0b21cf4626bd91219f309ca), is that possible for you to release a new version to PyPi with the Django 1.11 support included? Thank you.

**Comment by ToGoBananas** [comment]
+1

**Comment by jrief** [comment]
thanks for the reminder
