### ISSUE TITLE
OSS License compatibility question

### ISSUE THREAD

**Issue by Ashley123456789** [jrief/django-websocket-redis#302]
There’s possible confusion on the license of your repository when you combine other open-source code. 

The modules `ws4redis/websocket.py` and `ws4redis/utf8validator.py` claim their licenses as **Apache-2.0**. 
However, the license of your whole project is shown as the **MIT license** in LICENSE.txt, i.e., **less strict** than Apache-2.0 on license terms, which may impact the whole license compatibility in your repository, thus confusing subsequent users and bringing possible legal and financial risks.

If possible, you can fix them in one of the following ways:

- select another proper license for your repository, e.g., Apache-2.0
- update this license with term exceptions added for specific modules
- remove these modules if they are not actually useful

**Comment by jrief** [comment]
It is clearly stated on the header of these files that they are licensed under the Apache license

> This code was generously pilfered from https://bitbucket.org/Jeffrey/gevent-websocket
written by Jeffrey Gelens (http://noppo.pro/) and licensed under the Apache License, Version 2.0

and 

> Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

so I don't understand, what kind of problem you have with this approach.
