### ISSUE TITLE
Connects and Immediately Closes

### ISSUE THREAD

**Issue by grvhi** [jrief/django-websocket-redis#56]
I've used DWR a few times in production and setup has always been a breeze.... But this time, for some reason I'm stuck.

The short version is that in the browser console, I see the correct ws URL being connected to, followed by Connected! and immediately followed by Connection Closed. The JS script then retries, connects and is immediately disconnected. This loop continues ad infinitum.

I've tried everything. I've had help from the #uwsgi irc channel and everyone said my setup is correct. I've used - and am still using - the exact same setup in a few production sites. The only difference is that this site is hosted on AWS EC2, but not behind ELB. 

Running locally under run server, all is well. I'm getting absolutely nothing in any django logs (I see the WS4Redis wsgi_server logs to django.request) and the uwsgi logs show the connection as being successful. 

I'm sure I've been through everything. But I'm probably missing something obvious. If anyone can help put me straight, I'd be really grateful!!

**Comment by Divargar-mahnaz** [comment]
I had similar problem .

My websocket connect and disconnect immediately ,

Although Redis was installed,

The problem was with the Redis version.

Your Redis version must be greater than five
