### ISSUE TITLE
Subscribe to more than one channels

### ISSUE THREAD

**Issue by khamaileon** [jrief/django-websocket-redis#69]
Hi guys,

I'm looking for a way to subscribe at more than one channels for an existing socket connection.

The documentation says:

>  Additionally, a client may declare on initialization, on which channels he wishes to publish a message. The latter is not that important for a websocket implementation, because it can be achieved otherwise, using the well known XMLHttpRequest (Ajax) methods.

Do you have a example how to do this?

**Comment by endeav** [comment]
Hi, any news in this direction?
I also need to dynamically subscribe to new channels for an existing socket connection.
How can I do this?
Many thanks!

**Comment by domface** [comment]
+1
