### ISSUE TITLE
Example nginx running uwsgi in emperor mode

### ISSUE THREAD

**Issue by YuriHeupa** [jrief/django-websocket-redis#72]
Could have some example of nginx server running uwsgi in emperor mode

**Comment by jrief** [comment]
Just use the example http://django-websocket-redis.readthedocs.org/en/latest/running.html#django-with-websockets-for-redis-behind-nginx-using-uwsgi and run uwsgi in emperor mode as explained in the uwsgi docs.
Use http://django-websocket-redis.readthedocs.org/en/latest/running.html#django-with-websockets-for-redis-as-a-stand-alone-uwsgi-server-in-emperor-mode as a blueprint for it.

**Comment by YuriHeupa** [comment]
This emperor mode is not working on my server, would i have some examples of this working in a server
