### ISSUE TITLE
No module named uwsgi

### ISSUE THREAD

**Issue by neo-hu** [jrief/django-websocket-redis#74]
/var/www/env/bin/python2.7 /var/www/untitled/manage.py runserver 8000

django.core.exceptions.ImproperlyConfigured: WSGI application 'untitled.wsgi.application' could not be loaded; Error importing module untitled.wsgi: "No module named uwsgi"
?

**Comment by jrief** [comment]
RTFM: http://django-websocket-redis.readthedocs.org/en/latest/installation.html#dependencies

**Comment by neo-hu** [comment]
Thank you 
have been solved
