### ISSUE TITLE
Celery scheduled task, can't publish message

### ISSUE THREAD

**Issue by ManuelGysin** [jrief/django-websocket-redis#75]
Hello!

I have some strange behavior with celery and django-websocket-redis.

Setup:
- Django 1.7 (uwsgi + nginx)
- django-websocket-redis (uwsgi + nginx)
- Celery with worker (multi, uses django settings)

Everything with the websockets works fine and I can receive and publish messages.
I have a simply function which I call through celery every 10 seconds. This function just sends some junk of data to ensure the client cache. (It's broadcasted to all connected users)
I have an 1:1 copy of this function which sends every 1 minute the same data to the clients. (cronjob which calls an url to execute the function)

Problem:
- URL call works and message is published
- Celery call works but no message is published or received

Is this the excepted behavior? If so, what needs to be done to support such calls?
Where can I start to debug this? The logs don't tell me anything about a problem. It's seems the call is just sent to the nirvana.

Greets
Manuel

**Comment by jrief** [comment]
I would suggest to use redis-cli.
Then find out the listener name for the corresponding message queue. Try to send a message to this listener, it should be passed through to the browser.
If that works, you can use Celery and publish messages.

**Comment by ManuelGysin** [comment]
Thanks for the hint.
It seems everything was fine but I have to start first django and ws4redis and at least celery. So everything works now. :)

**Comment by YuriHeupa** [comment]
+ManuelGysin How did you change the start order of django, ws4redis and celery? When i added celery to my server the websocket stopped working, cant find the reason

**Comment by ejosan** [comment]
i have django redis websocket running with rq (https://github.com/nvie/rq) as an alternative to celery.
