### ISSUE TITLE
Is it possible to create a websocket for each client tied to a single websocket and have it subscribe to certain events?

### ISSUE THREAD

**Issue by niks3089** [jrief/django-websocket-redis#81]
Following is something I want to achieve:

Following is a sequence of events that is happening

Part 1:
Client sends a form.
Django receives a form, validates it and creates a Task for Celery or Django-rq to run.
Returns a results.html to the user.

Part 2:
Task is run by the workers which generates JSON data every second.
This needs to be sent to the right client asynchronously and as a part of result.html.
Client should see the updated results without doing any refresh.

Is this possible with django-websocket-redis? How should the client subscribe?
Note that I will not have thousands of clients so number of websockets should not be a problem

**Comment by jrief** [comment]
Part 1 is easy :)

Well for part 2, we must presume, that the client is still connected. Celery known the session-id of that client and the chosen Websocket URI. Simple push a serializable Python dict into that bucket on Redis, it then will be send to the client, trigger a Javascript event and that dict will pop out as a plain Javascript object.

For details refer to the API:
http://django-websocket-redis.readthedocs.org/en/latest/api.html

**Comment by niks3089** [comment]
Great..Thanks!
